### ISSUE TITLE
useSearchQuery can't be resolved

### ISSUE THREAD

**Issue by dannysofftie** [typesense/docusaurus-theme-search-typesense#1]
## Description
`Module not found: Error: Can't resolve '@theme/hooks/useSearchQuery'  in  './node_modules/docusaurus-theme-search-typesense/src/theme/SearchPage'`

## Steps to reproduce

1. Install this package into a docusurus project `yarn add docusaurus-theme-search-typesense`
2. Add below config to docusaurus.config.js
```js
{
  themes: ['docusaurus-theme-search-typesense'],
  themeConfig: {
    typesense: {
      typesenseCollectionName: 'docs',
      typesenseServerConfig: {
        nodes: [
          {
            host: '127.0.0.1',
            port: 9090,
            protocol: 'http',
          },
        ],
        apiKey: '< key >',
      },
      typesenseSearchParameters: {},
      // Optional
      contextualSearch: true,
    },
  },
}
```

## Expected Behavior

Show search bar in generated docs website

## Actual Behavior

![image](https://user-images.githubusercontent.com/17042186/132496879-538c134f-d195-4dfb-ba63-782d12c98c64.png)

## Metadata

**Typsense Version**:
0.21.0

**OS**:
Ubuntu 20.04.3

**Comment by dannysofftie** [comment]
The setup isn't clear, solved above by configuring docusaurus correctly

**Comment by jasonbosco** [comment]
@dannysofftie Could you expand on which part of the setup instructions were unclear? Would love to address any confusion in the docs.

**Comment by dtlhlbs** [comment]
Ugh, have the same issue, would like to know how to go about "configuring docusaurus correctly"

**Comment by dtlhlbs** [comment]
@jasonbosco Turns out it was the re-compiling under webpack that didn't work. All I need to do was stop the dev server and `yarn start` again and it was fine.
