### ISSUE TITLE
"Please use snake_cased versions" warning

### ISSUE THREAD

**Issue by octogonz** [typesense/docusaurus-theme-search-typesense#11]
## Description

After upgrading to Docusaurus `2.0.0-beta.17`, I now see this warning during the build:

```
[typesense-instantsearch-adapter] Please use snake_cased versions of parameters in 
additionalSearchParameters instead of camelCased parameters. 
For example: Use query_by instead of queryBy. camelCased parameters will be 
deprecated in a future version. We're making this change so that parameter names 
are identical to the ones sent to Typesense (which are all snake_cased), and to also keep 
the types for these parameters in sync with the types defined in typesense-js.
√ Client: Compiled successfully in 4.70m
√ Server: Compiled successfully in 4.71m
```

My repo does not configure `additionalSearchParameters` anywhere.

I think the problem is caused by `docusaurus-theme-search-typesense`:

https://github.com/typesense/docusaurus-theme-search-typesense/blob/51b7a16f0646f38cebb9affe0bea42d5cb1e9d77/src/theme/SearchPage/index.js#L174-L179

Should we just make a PR to rename `queryBy` to `query_by`?

## Metadata

**Typsense Version**: `docusaurus-theme-search-typesense@0.3.0`

**OS**: Windows

**Comment by octogonz** [comment]
Looks like this change was introduced in [typesense-instantsearch-adapter issue #85](https://github.com/typesense/typesense-instantsearch-adapter/issues/85) ([`bdea259`](https://github.com/typesense/typesense-instantsearch-adapter/commit/bdea2599f109f85007646a5cd379952c10efcde5)) and released with `typesense-instantsearch-adapter@2.4.0`.

As a temporary workaround, I was able to eliminate the warning by forcing installation of `typesense-instantsearch-adapter@2.3.0`.

**Comment by jasonbosco** [comment]
@octogonz Thank you for catching this. 

I've pushed out a [fix](https://github.com/typesense/docusaurus-theme-search-typesense/commit/b92ecaa7e631200114446da2d690b968b2c8fde8#diff-af48d54e94364101290c32aec24741b9996eedcde042711d17915a28ad14d78b) for this in `0.4.0-1`. Could you give it a shot now?

**Comment by octogonz** [comment]
@jasonbosco thank you!  We've confirmed that `0.4.0-2` fixes the problem.  👍
