### ISSUE TITLE
Unable to locate the repository for typesense-docsearch-react

### ISSUE THREAD

**Issue by romdej** [typesense/docusaurus-theme-search-typesense#14]
## Description

I would like to create some PRs to fix some bugs in typesense-docsearch-react. Unfortunately, I can't find the repository associated to this package. In its package.json, the repository indicated is typesense/typesense-js.

I noticed that docusaurus-theme-search-typesense is the only package that depends on typesense-docsearch-react. So I thought you would be able to tell me where to find the sources of this project to contribute.

**Comment by jasonbosco** [comment]
@romdej The typesense-docsearch-react package is under the `next` branch in this repo: https://github.com/typesense/typesense-docsearch.js/tree/next/packages/docsearch-react
