### ISSUE TITLE
Fix compatibility issue with Docusaurus v2.0.0-beta.22 and above

### ISSUE THREAD

**Issue by aelmsu** [typesense/docusaurus-theme-search-typesense#18]
## Description

Building a project based on Docusaurus v2.0.0-beta.22 and later crashes.

## Steps to reproduce

1. Create a new project based on Docusaurus v2.0.0-beta.22 or later (the latest version at the time of writing being v2.0.0-rc.1).
2. Integrate the Typesense plugin according to [this guideline](https://typesense.org/docs/guide/docsearch.html).
3. Run `npm run build`.

## Expected Behavior

The project builds successfully.

## Actual Behavior

The build fails with the following error:

```
TypeError: (0 , lib_namespaceObject.useTitleFormatter) is not a function

[WARNING] node_modules/docusaurus-theme-search-typesense/src/theme/SearchPage/index.js:
export 'useTitleFormatter' (imported as 'useTitleFormatter') was not found in '@docusaurus/theme-common'
```

## Proposed solution

As per [this pull request](https://github.com/facebook/docusaurus/commit/9473508c33132ac3c0ad7446ccd94fb7b386b085#diff-0916b3604417380b3087c19a32c2340430bc9af617e30dce1add73033a609976), some exports were moved to `internal.ts`.

So the import in `src/theme/SearchPage/index.js` needs to be changed from:

```
import {useTitleFormatter, usePluralForm} from '@docusaurus/theme-common';
```

to

```
import {useTitleFormatter, usePluralForm} from '@docusaurus/theme-common/internal';
```

It would be awesome if you could fix the compatibility issue and also update the dependencies so that the plugin is compatible with Docusaurus v2.0.0-rc.1.

## Metadata

**Typsense Version**: 0.4.0

**OS**: Windows 11 (22000.795)

**Comment by jasonbosco** [comment]
@aelmsu Thank you for reporting this. I've pushed out v0.5.0 which is compatible with `docusaurus-2.0.0.rc1`.
