### ISSUE TITLE
Build error: Docusaurus server-side rendering could not render static page with path /search (ReferenceError: window is not defined)

### ISSUE THREAD

**Issue by MajidSadrr** [typesense/docusaurus-theme-search-typesense#21]
## Description

Hi,
When I use to build my docusaurus project with typesense included, I get this error:

![image](https://user-images.githubusercontent.com/76779095/180994492-cba59806-5b86-486f-8aa2-c87d6a253b23.png)

## Actual Behavior

The command `yarn build` fails after running with the error described above.

## Metadata

**Typsense Version**: 0.5.2

**Docusaurus Version**: 2.0.0-rc.1

**Comment by jasonbosco** [comment]
@MajidSadrr Thank you for reporting this. I've pushed out a fix in v0.5.3 of `docusaurus-theme-search-typesense`. Could you try now?

**Comment by MajidSadrr** [comment]
@jasonbosco Thanks! fixed. :)
