### ISSUE TITLE
Dependency issue with Docusaurus 2.0.1

### ISSUE THREAD

**Issue by MisterHarrow** [typesense/docusaurus-theme-search-typesense#22]
When running:
`npm install docusaurus-theme-search-typesense@next --save`

The result is:

ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: my-website@0.0.0
npm ERR! Found: @docusaurus/core@2.0.1
npm ERR! node_modules/@docusaurus/core
npm ERR!   @docusaurus/core@"2.0.1" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer @docusaurus/core@"2.0.0-rc.1" from docusaurus-theme-search-typesense@0.5.3-0
npm ERR! node_modules/docusaurus-theme-search-typesense
npm ERR!   docusaurus-theme-search-typesense@"0.5.3-0" from the root project

Is this not compatible with the latest docusaurus 2.0.1?

**Comment by jasonbosco** [comment]
Could you try with v0.5.3 of docusaurus-theme-search-typesense?

**Comment by MisterHarrow** [comment]
Thanks! That did it :-)

**Comment by saltcod** [comment]
Hey!

Oddly, we're still seeing this error. It looks like I'm using the right versions — any ideas?   using `--force` or `--legacy-peer-deps` resolves it, but if there's something else we can fix that'd be ideal!

<img width="745" alt="CleanShot 2022-08-12 at 10 39 25@2x" src="https://user-images.githubusercontent.com/105593/184360497-9fd6c433-a9c4-4955-b756-070f74baca80.png">

**Comment by jasonbosco** [comment]
@saltcod Could you try with 0.6.0-0 of docusaurus-theme-search-typesense?

**Comment by saltcod** [comment]
Sweet! That looks to have done it. Thanks @jasonbosco !
