### ISSUE TITLE
Search Modal shows non-snippeted value and search results page shows snippeted value, when it should be the other way around

### ISSUE THREAD

**Issue by jasonbosco** [typesense/docusaurus-theme-search-typesense#31]
Reported by @aandis during office hours

Showing the non-snippeted value in the search modal ends up cutting off highlighted terms, which leads to confusing UX

**Comment by jasonbosco** [comment]
@aandis I've pushed out a fix for this in v0.10.0-0 of `docusaurus-theme-search-typesense`. Could you give it a shot now?

**Comment by aandis** [comment]
Looks good. Thanks!
