### ISSUE TITLE
Configuration questions

### ISSUE THREAD

**Issue by attila-csaszar** [typesense/docusaurus-theme-search-typesense#33]
Hi!
We have the Typesense search added to [our documentation site](https://docs.nevis.net/), but so far, I've been unable to configure it in a way that it gives relevant results. I have also been unable to find any material on how to really configure the plugin other than simply adding it to the website.

Specifically I'm looking to have the following set up:
- Filter to search within given subsets of pages. This is important, as the documentation page includes the docs of several separate products - so we have several folders within the docs folder in the Docusaurus project.
- Filter to search within specific versions os specific products
- Differentiate and prioritize based on what type of element is matched. That is, page title, subheading within a page, or any other piece of text.

I see that there is a possibility to have different dropdowns appear on the 'All results' page, but I cannot find how and where to configure them.

Thanks in advance for the help!

**Comment by jasonbosco** [comment]
For filtering to particular pages / versions, you want to add a meta tag with this information to each page as described [here](https://typesense.org/docs/guide/docsearch.html#add-docsearch-meta-tags-optional), which will result in the scraper adding this information to each Typesense document. 

Then on page load, you want to dynamically set `typesenseSearchParameters` when instantiating the docsearch library. 

> Differentiate and prioritize based on what type of element is matched. That is, page title, subheading within a page, or any other piece of text.

This is pre-defined [here](https://github.com/typesense/typesense-docsearch.js/blob/777f721ec346e73d9e002de591b363b611c50a72/packages/docsearch-react/src/DocSearchModal.tsx#L200). You can customize it by overriding those settings in `typesenseSearchParameters`

**Comment by attila-csaszar** [comment]
Thanks for the help. I think I'm getting there, but I still have some questions:
- How do I configure the drop-downs that appear on the "All results page"? 
- How do I configure a faceted search, so users can narrow down search results?

**Comment by jasonbosco** [comment]
This theme doesn't allow you to customize the search results page UI. So you would have to fork this theme and make changes to it yourself.
