### ISSUE TITLE
Placement of search box

### ISSUE THREAD

**Issue by arvinddoraiswamy** [typesense/docusaurus-theme-search-typesense#34]
Hi :)
So I followed the instructions on https://typesense.org/docs/guide/docsearch.html#option-a-docusaurus-powered-sites and have the search box in the top right of the page. It seems to work OK in that I get some results back (I'll tune later) - but I was curious if there was a way to change the position of the search box from the top right to the center of the page easily.

If not, what will I have to change in the code to change the position of the box. Could you help out with this?

Thanks
Arvind

**Comment by jasonbosco** [comment]
I think this might be a question for the the docusaurus team, because the location of the search bar is not managed within this theme from what I can tell. I essentially forked the Algolia theme and made it work with Typesense, and I don't recall seeing any page layout settings in the process.

**Comment by arvinddoraiswamy** [comment]
Ah okay - i'll go poke there. How does it magically end up in the top right though then - was what I was wondering. Like if there's another theme tomorrow - would that end up top right as well, or can there only _ever_ be a single theme in docusaurus?

**Comment by jasonbosco** [comment]
> How does it magically end up in the top right though then - was what I was wondering

I think the base docusaurus theme has a placeholder on the top right for the search bar, and if there are any search related themes, it uses them to render that portion of the navbar.

**Comment by arvinddoraiswamy** [comment]
Thanks. Do you think it might be possible to change it around with either:

- https://docusaurus.io/docs/styling-layout#theme-class-names OR
- https://docusaurus.io/docs/swizzling#swizzling-process [this looks scary bade on the screenshot below :)]

![image](https://github.com/typesense/docusaurus-theme-search-typesense/assets/885730/6f0b865e-a4e5-4fce-9277-c831d2e64474)

but that apart - i'll go poke docasaurus folks :) - I don't know much react at all, just trying to use a theme and hence some questions.
