### ISSUE TITLE
Error NPM Installing when using Docusaurus 2.4.1

### ISSUE THREAD

**Issue by nalham** [typesense/docusaurus-theme-search-typesense#35]
## Description

The `package.json` has all docusaurus components hardcoded to [2.4.0](https://github.com/facebook/docusaurus/releases/tag/v2.4.0), not allowing to upgrade to the recent release of [2.4.1](https://github.com/facebook/docusaurus/releases/tag/v2.4.1)

## Steps to reproduce

1. In any package that uses **typesense/docusaurus-theme-search-typesense**, upgrade docusaurus to `2.4.1`
2. run `npm install` or `yarn install`

## Expected Behavior

npm/yarn install works

## Actual Behavior

npm/yarn install throws error

example npm error
```
npm ERR! Found: @docusaurus/core@2.4.1
npm ERR! node_modules/@docusaurus/core
npm ERR!   @docusaurus/core@"2.4.1" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer @docusaurus/core@"2.4.0" from docusaurus-theme-search-typesense@0.11.0
```

## Metadata

**Typesense Version**: 0.11.0

**OS**: MacOS 13.3.1

**Comment by jasonbosco** [comment]
I just published `v0.12.0-0`. Could you upgrade to this version and let me know if that fixes the issue?

**Comment by nalham** [comment]
@jasonbosco That solved it, thanks!

**Comment by jasonbosco** [comment]
Great, thank you for confirming!
