### ISSUE TITLE
Support for Docusaurus 3.1.0

### ISSUE THREAD

**Issue by AdamG100** [typesense/docusaurus-theme-search-typesense#40]
## Description

Support for Docusaurus 3.1.0

## Steps to reproduce

Upgrade to  Docusaurus 3.1.0

## Expected Behavior

N/A

## Actual Behavior

npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: docusaurus-theme-search-typesense@0.14.1-0
npm WARN Found: @docusaurus/core@3.1.0
npm WARN node_modules/@docusaurus/core
npm WARN   @docusaurus/core@"3.1.0" from the root project
npm WARN   11 more (@docusaurus/plugin-content-blog, ...)
npm WARN
npm WARN Could not resolve dependency:
npm WARN peer @docusaurus/core@"3.0.1" from docusaurus-theme-search-typesense@0.14.1-0
npm WARN node_modules/docusaurus-theme-search-typesense
npm WARN   docusaurus-theme-search-typesense@"^0.14.1-0" from the root project

## Metadata

**Typesense Version**:

0.14.1

**OS**:

Windows 11

**Comment by jasonbosco** [comment]
Could you try with `v0.15.0-0`?

**Comment by AdamG100** [comment]
Thanks! its loading in now much app

**Comment by jasonbosco** [comment]
Thank you for confirming!
