### ISSUE TITLE
Issues on search page after clicking on "see all results" from modal

### ISSUE THREAD

**Issue by Aleksao998** [typesense/docusaurus-theme-search-typesense#8]
## Description

Hi, 
I am working on Polygon Edge project. We are using your library for adding doc search on our documentation website. We have discovered 2 small bugs.

When we use modal for search, everything works great! We have also tested transparent background for the logo in a dark mode which you have introduced in 0.3.0-1 version. Thank you so much for that!
![Screen Shot 2022-01-17 at 12 23 23 PM (2)](https://user-images.githubusercontent.com/42786413/149761294-ab54f820-3c98-4fd4-b433-ba9a0157a175.png)

Then the user clicks on **See all xxx results** at the bottom of the modal, the search page is opened. 
![Screen Shot 2022-01-17 at 12 26 18 PM (2)](https://user-images.githubusercontent.com/42786413/149761517-5dce0c04-c511-4166-9a06-a53464c4a2c0.png)

Here we are getting an error when we are searching
`{"results":[{"code":404,"error":"Could not find a filter field named `docusaurus_tag` in the schema."},{"code":404,"error":"Could not find a filter field named `docusaurus_tag` in the schema."},{"code":404,"error":"Could not find a facet field named `docusaurus_tag` in the schema."}]}`

And also on this page your logo is not transparent in the dark mode (small cosmetic improvement).

**Typsense Version**:
In production we are currently using  ^0.2.0 and today we are going to switch to 0.3.0-1

**Comment by jasonbosco** [comment]
@Aleksao998 Thank you for testing the transparency. I'll fix it in the search results page as well. 

The blank search page issue, sounds very similar to the one that @octogonz fixed in #7: https://github.com/typesense/docusaurus-theme-search-typesense/issues/2#issuecomment-1013600688

Could you try doing a docker pull on the scraper image and then running the scraper again, to see if that fixes the issue?

**Comment by jasonbosco** [comment]
Published `v0.3.0` with a few more fixes for Docusaurus 2.0.0-beta.15.

**Comment by Aleksao998** [comment]
Hi, just wanted to thank you. Everything is working with the new version and docker-pull

**Comment by jasonbosco** [comment]
Thank you for confirming @Aleksao998!
